//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.10 at 09:56:19 PM EET 
//


package com.bookwriter.jaxb.parts;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bookwriter.jaxb.parts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Parts_QNAME = new QName("", "parts");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bookwriter.jaxb.parts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PartsType.Part }
     * 
     */
    public PartsType.Part createPartsTypePart() {
        return new PartsType.Part();
    }

    /**
     * Create an instance of {@link PartsType }
     * 
     */
    public PartsType createPartsType() {
        return new PartsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parts")
    public JAXBElement<PartsType> createParts(PartsType value) {
        return new JAXBElement<PartsType>(_Parts_QNAME, PartsType.class, null, value);
    }

}
